---
title: "Auction Modeling"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
        echo = TRUE
)
knitr::opts_knit$set(
        stop_on_error = 2L
)
knitr::opts_chunk$set(
        fig.path = "man/figures/"
)
```


# auctionmodel

## Overview 

An R package for R to estimate private-value auction models while allowing for unobservable
auction-specific heterogeneity.

## Installation

```{r, eval = FALSE}
# Install the the development version from GitHub:

# install.packages("remotes")
remotes::install_github("alexjmac/auction_model")
```


## Getting started

There are two functions availabe from the package:

* `auction_generate_data()` which xxxx

* `auction_model()` which does the real work.

```{r}
library(auctionmodel)
set.seed(100)

dat <- auction_generate_data(obs = 100, mu = 10, alpha = 2, sigma = 0.2,
                             beta = c(-1,1), new_x_mean= c(-1,1), new_x_sd = c(0.5,0.8))

auction_model(dat,
              init_param =  c(8, 2, .5, .4, .6),
              num_cores = 1,
              method = "BFGS",
              control = list(trace=1, parscale = c(1,0.1,0.1,1,1)))
```

## For further information


## License

